// Data for the tech-stack section. Each item maps a display name to a brand
// logo slug (raw SVGs in src/assets/logos/, generated by scripts/gen-tech-logos.mjs
// from theSVG). Items without a brand mark (SQL, REST) use a short `mono`
// monogram instead. `featured` items get an accent ring — these are the tools
// previously emphasised with <em> in the old chip layout.

export interface TechItem {
  name: string;
  /** Logo slug → src/assets/logos/<slug>.svg. Omit for monogram-only items. */
  slug?: string;
  /** Short text shown on the plate when there is no brand logo. */
  mono?: string;
  featured?: boolean;
}

export interface TechGroup {
  label: string;
  items: TechItem[];
}

export const techGroups: TechGroup[] = [
  {
    label: 'Languages',
    items: [
      { name: 'Python', slug: 'python', featured: true },
      { name: 'C++', slug: 'cplusplus' },
      { name: 'JavaScript', slug: 'javascript' },
      { name: 'SQL', mono: 'SQL' },
      { name: 'Bash', slug: 'bash' },
      { name: 'Swift', slug: 'swift' },
    ],
  },
  {
    label: 'AI / ML',
    items: [
      { name: 'PyTorch', slug: 'pytorch', featured: true },
      { name: 'TensorFlow', slug: 'tensorflow' },
      { name: 'TensorRT', slug: 'nvidia' },
      { name: 'ONNX', slug: 'onnx' },
      { name: 'OpenCV', slug: 'opencv' },
      { name: 'GStreamer', slug: 'gstreamer' },
      { name: 'Nvidia Jetson', slug: 'nvidia' },
    ],
  },
  {
    label: 'Back end',
    items: [
      { name: 'Flask', slug: 'flask', featured: true },
      { name: 'REST APIs', mono: 'API' },
    ],
  },
  {
    label: 'Databases',
    items: [{ name: 'PostgreSQL', slug: 'postgresql', featured: true }],
  },
  {
    label: 'DevOps',
    items: [
      { name: 'Docker', slug: 'docker', featured: true },
      { name: 'Jenkins', slug: 'jenkins' },
      { name: 'GitLab CI/CD', slug: 'gitlab' },
      { name: 'Kubernetes', slug: 'kubernetes' },
      { name: 'Grafana', slug: 'grafana' },
      { name: 'ELK', slug: 'elasticsearch' },
      { name: 'AWS S3', slug: 'aws-amazon-simple-storage-service' },
    ],
  },
  {
    label: 'Tools',
    items: [
      { name: 'Git', slug: 'git', featured: true },
      { name: 'Postman', slug: 'postman' },
      { name: 'Selenium', slug: 'selenium' },
      { name: 'Scrapy', slug: 'scrapy' },
    ],
  },
];
